# Version format
version: "{build}"

# Operating system (build VM template)
os: Windows Server 2016

# If the build configuration does not specify build worker image
# then Visual Studio 2015 image is used.
image: Visual Studio 2017

# Restrict to Git branches below
branches:
  only:
    - master

# Scripts that run after cloning repository
install:
  - nuget restore

# Cache files until appveyor.yml is modified.
cache:

init:
- ps: |
    if ($env:APPVEYOR_REPO_TAG -eq "true" -and $env:APPVEYOR_REPO_TAG_NAME)
    {
        $tag_name = $env:APPVEYOR_REPO_TAG_NAME
        if ($tag_name -match '([0-9]+[\.-][0-9]+[\.-][0-9]+[\.-][0-9]+)')
        {
            Update-AppveyorBuild -Version "$tag_name"
        }
    }

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(appveyor_build_version)
  package_version: $(appveyor_build_version)
  assembly_version: $(appveyor_build_version)
  file_version: $(appveyor_build_version)
  informational_version: '$(appveyor_build_version)-beta'

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: $(appveyor_build_version)
  assembly_file_version: $(appveyor_build_version)
  assembly_informational_version: '$(appveyor_build_version)-beta'

# Run scripts below before
before_build:
  - where msbuild
  - cmd: rmdir "%APPVEYOR_BUILD_FOLDER%\bin" /S /Q

# To run your custom scripts instead of automatic MSBuild
build_script:
  - cmd: msbuild /t:Clean Revit.Toolkit.sln
  - cmd: msbuild /p:Configuration=Debug /t:Build Revit.Toolkit.sln

# NuGet files qualified as artifacts
artifacts:
  - path: '**\*.nupkg' # find the NuGet files
    name: Revit_Toolkit

# Deploy to GitHub releases
deploy:
  provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: "Revit Toolkit v$(APPVEYOR_REPO_TAG_NAME)"
  description: "* for .NET Standard 2.0 (.NET Core 2.0, .NET Framework >= 4.6.1 etc) use CodeCave.Revit.Toolkit.{x.y.z}.nupkg file\n* for .NET Framework 4.5.x use CodeCave.Revit.Toolkit.NetFramework.{x.y.z}.nupkg file"
  force_update: true
  auth_token:
    secure: 2+d0KgCbWQpUR8TZfzvUEzbi4NQP6F/Tt0PUwLn6jXZCyO8FnrFVFJPsFa0QBQFl
  artifact: Revit_Toolkit
  draft: false
  prerelease: false
  on:
    # branch: master
    appveyor_repo_tag: true

# Turn off tests
test: off
